### ISSUE TITLE
Should body copy be Roboto?

### ISSUE THREAD

**Issue by backspace** [winnipegpolicecauseharm/wpch-ghost-theme#11]
I was wondering whether it would make sense to just use Roboto everywhere vs Open Sans in some places, as to me they’re not different enough:

![image](https://user-images.githubusercontent.com/43280/91595395-1399d100-e929-11ea-81b3-f0e4c7bfafbd.png)

**Comment by farfamahar** [comment]
I just chose the font pairing based off Google Fonts recommended font parings for Roboto [here](https://fonts.google.com/specimen/Roboto#pairings). Imo I think a distinction between heading fonts and body text is best. There might be better options out there.

**Comment by backspace** [comment]
ah nice, I didn’t know about that pairings feature. I feel like all their suggestions are barely different enough from Roboto! But oh well. I wonder if we know anyone with an Adobe subscription who can let us use the original fonts 😆
