### ISSUE TITLE
Add analytics

### ISSUE THREAD

**Issue by farfamahar** [winnipegpolicecauseharm/wpch-ghost-theme#17]
It would be interesting to see how much traffic the site gets on launch. I'm not too fond of the idea of using google analytics for a site like this though. Maybe lets opt for something more privacy friendly. Some potential alternatives I found.

https://matomo.org/

https://www.goatcounter.com/ (this looks super lightweight and simple)

**Comment by metmarkosaric** [comment]
There's also Plausible Analytics which I'm working on. Modern dashboard, simple metrics to understand, open source so can be self-hosted, lightweight script (<1 KB), no cookies and doesn't collect personal data so no need for cookie/GDPR consent banner. 

Our GitHub: https://github.com/plausible/analytics 
Our website: https://plausible.io/

**Comment by backspace** [comment]
ah I did set up a Matomo instance, @FarfamaH! Sorry, I didn’t get any notification of this 😯  I’ll send you an invitation.
