### ISSUE TITLE
Embedded Youtube video blog posts do not center / scale

### ISSUE THREAD

**Issue by farfamahar** [winnipegpolicecauseharm/wpch-ghost-theme#23]
Text posts look fine, but once a youtube video is embedded, the layout breaks. Example

Desktop 
![Desktop](https://user-images.githubusercontent.com/32600047/94819694-2cccec00-03c5-11eb-8c2d-e4c2aade7e12.PNG)

Mobile
![Mobile](https://user-images.githubusercontent.com/32600047/94819753-3d7d6200-03c5-11eb-8c1a-79ec4b67affb.PNG)

**Comment by farfamahar** [comment]
@backspace

**Comment by farfamahar** [comment]
Instead of using ghosts built in youtube embed, we can use the generated html with a video from this site and embed it with ghost editor html

http://embedresponsively.com/

Works really well and makes it responsive

**Comment by backspace** [comment]
works for me, thanks!
